# Generated by Django 4.1.5 on 2023-01-17 15:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 17, 15, 51, 4, 15376, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
