# Generated by Django 4.1.5 on 2023-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0002_bus_destination_bus_source_bus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
    ]
