# Generated by Django 4.1.5 on 2023-02-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSystem', '0004_bus_arrivaltime_bus_capacity_bus_departuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='arrivalTime',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departureTime',
            field=models.CharField(max_length=20),
        ),
    ]
